# Generated by Django 4.2.1 on 2023-05-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box',
        ),
    ]
